"""
Disclaimer Content - Types and text constants for legal disclaimers

Extracted from disclaimers.py during P2 decomposition.
Contains:
- DisclaimerType enum (types of disclaimers)
- Text constants for each disclaimer type
"""

from enum import Enum


class DisclaimerType(str, Enum):
    """Types of disclaimers"""
    MEDICAL_ADVICE = "medical_advice"
    AI_CONTENT = "ai_content"
    LIABILITY = "liability"
    EXPORT_CONTROL = "export_control"
    HIPAA_COMPLIANCE = "hipaa_compliance"
    DATA_PRIVACY = "data_privacy"


# Short disclaimer for chat UI footer
MEDICAL_DISCLAIMER_SHORT = (
    "⚠️ Not medical advice. Consult a licensed professional for medical decisions."
)

# Full medical disclaimer for Settings → Legal page
MEDICAL_DISCLAIMER_FULL = """MEDICAL DISCLAIMER

MedStation and its AI features are not medical devices and do not provide medical advice, diagnosis, or treatment. Information provided is for informational purposes only. Always consult with a qualified healthcare professional for medical decisions.

By using MedStation in medical contexts, you acknowledge that:

• AI responses are not a substitute for professional medical judgment
• You are responsible for verifying all medical information
• MedStation is not liable for medical decisions made using this software
• The software is not FDA-approved for clinical use
• Information may be inaccurate, incomplete, or outdated

EMERGENCY DISCLAIMER

If you are experiencing a medical emergency, immediately call emergency services (911 in the US) or go to the nearest emergency room. Do not rely on MedStation for emergency medical assistance.

PROFESSIONAL LICENSING

MedStation does not replace the need for professional medical licensing, credentials, or certification. Healthcare professionals are responsible for maintaining their own licenses and following applicable regulations in their jurisdiction."""

# AI-generated content disclaimer
AI_CONTENT_DISCLAIMER = """AI-GENERATED CONTENT DISCLAIMER

Responses generated by AI in MedStation are:

• Generated by large language models that may produce incorrect information
• Not verified for accuracy, completeness, or currency
• Not a substitute for professional expertise or judgment
• Subject to biases present in training data
• Potentially containing outdated information

Users are responsible for:

• Verifying all AI-generated information before use
• Not relying solely on AI responses for critical decisions
• Understanding the limitations of AI technology
• Complying with professional standards in their field

MedStation makes no warranties about the accuracy, reliability, or suitability of AI-generated content for any particular purpose."""

# General liability disclaimer
LIABILITY_DISCLAIMER = """LIABILITY DISCLAIMER

TO THE MAXIMUM EXTENT PERMITTED BY LAW:

MedStation is provided "AS IS" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.

In no event shall the authors, copyright holders, or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including but not limited to procurement of substitute goods or services, loss of use, data, or profits, or business interruption) arising in any way out of the use of this software.

USER RESPONSIBILITY

Users are solely responsible for:

• Determining the suitability of MedStation for their use case
• Complying with all applicable laws and regulations
• Implementing appropriate security and privacy controls
• Maintaining backups of critical data
• Obtaining necessary licenses, certifications, or approvals
• Verifying all information before making decisions

PROHIBITED USES

MedStation must not be used for:

• Life-critical applications without appropriate safeguards
• Medical diagnosis or treatment without professional oversight
• Legal advice or representation
• Financial advice or trading without professional guidance
• Any illegal activities or purposes"""

# Export control notice for encryption
EXPORT_CONTROL_NOTICE = """EXPORT CONTROL NOTICE

MedStation uses strong encryption technology, including:

• AES-256-GCM encryption for data at rest
• TLS 1.3 for data in transit
• PyNaCl (libsodium) for end-to-end encryption
• PBKDF2 key derivation (600,000 iterations)

ENCRYPTION REGULATIONS

The export and import of encryption software may be subject to export control laws in various countries. Users are responsible for ensuring compliance with:

• U.S. Export Administration Regulations (EAR)
• Wassenaar Arrangement on Export Controls
• Local import/export regulations in their jurisdiction

COMPLIANCE RESPONSIBILITY

Before exporting, importing, or distributing MedStation, users must:

• Determine if export licenses or authorizations are required
• Comply with all applicable export control regulations
• Understand restrictions on encryption in their country
• Obtain necessary approvals from relevant authorities

The authors and contributors of MedStation are not responsible for users' compliance with export control regulations.

ENCRYPTION STRENGTH DISCLOSURE

This software uses cryptographic algorithms with key lengths that may be subject to export controls:

• AES-256 (256-bit symmetric encryption)
• X25519 (256-bit elliptic curve)
• SHA-256 (256-bit hashing)

For more information about U.S. export controls, visit the Bureau of Industry and Security (BIS) website: https://www.bis.doc.gov/"""

# HIPAA compliance notice
HIPAA_COMPLIANCE_NOTICE = """HIPAA COMPLIANCE NOTICE

MedStation provides technical safeguards that may support HIPAA compliance, but technical features alone do not ensure HIPAA compliance. Organizations using MedStation to handle Protected Health Information (PHI) must:

ORGANIZATIONAL REQUIREMENTS

• Determine if you are a HIPAA covered entity or business associate
• Implement comprehensive HIPAA compliance program
• Conduct risk assessments and security audits
• Establish policies and procedures for PHI handling
• Train workforce on HIPAA requirements
• Maintain documentation of compliance efforts
• Establish breach notification procedures

TECHNICAL SAFEGUARDS PROVIDED

MedStation includes:

• Encryption at rest (AES-256-GCM)
• Encryption in transit (TLS 1.3)
• End-to-end encryption for P2P communications
• Audit logging of data access
• Role-based access controls
• Automatic backup and recovery
• Secure key management (Secure Enclave)

ADDITIONAL SAFEGUARDS REQUIRED

Organizations must also implement:

• Physical safeguards (facility access controls)
• Administrative safeguards (security management process)
• Business Associate Agreements (BAAs)
• Workforce security measures
• Device and media controls
• Contingency planning
• Regular security assessments

BUSINESS ASSOCIATE AGREEMENT

The authors and contributors of MedStation do not have access to your data and are not business associates under HIPAA. MedStation is self-hosted software that you control. You are responsible for:

• Executing BAAs with any third-party service providers
• Ensuring all business associates are HIPAA compliant
• Monitoring and auditing business associate compliance

NO GUARANTEE OF COMPLIANCE

Use of MedStation does not guarantee HIPAA compliance. Compliance requires comprehensive organizational, administrative, and technical measures beyond what any single software product can provide."""

# Data privacy notice
DATA_PRIVACY_NOTICE = """DATA PRIVACY NOTICE

LOCAL-FIRST ARCHITECTURE

MedStation is designed with a local-first architecture:

• All data is stored locally on your device by default
• No data is sent to external servers without explicit user action
• P2P communications are end-to-end encrypted
• You maintain full control of your data

DATA COLLECTION

MedStation does not collect or transmit:

• Personal information to third parties
• Usage analytics or telemetry
• Crash reports or diagnostics (unless explicitly enabled)
• Any data to the software authors

DATA STORAGE

All data is stored in encrypted databases on your local device:

• SQLite databases with AES-256-GCM encryption
• Secure Enclave for cryptographic keys
• Local backups (encrypted)
• No cloud storage by default

USER RESPONSIBILITY

Users are responsible for:

• Protecting their device and encryption passphrase
• Implementing appropriate access controls
• Complying with privacy laws in their jurisdiction (GDPR, CCPA, etc.)
• Obtaining necessary consents from data subjects
• Providing privacy notices to individuals
• Handling data subject rights requests (access, deletion, etc.)

THIRD-PARTY SERVICES

If you enable integrations with third-party services:

• Those services may have their own data collection practices
• Review third-party privacy policies before enabling integrations
• Understand what data will be shared with third parties
• Ensure third-party services comply with applicable privacy laws

GDPR COMPLIANCE

For organizations subject to GDPR:

• MedStation provides technical measures to support GDPR compliance
• You are the data controller; you must ensure lawful processing
• Implement appropriate data protection measures
• Provide privacy notices and obtain consent where required
• Honor data subject rights (access, rectification, erasure, etc.)
• Conduct Data Protection Impact Assessments (DPIAs) where required"""

# Banner text for medical workflow templates
MEDICAL_TEMPLATE_BANNER = """⚠️ MEDICAL DISCLAIMER

This template is for informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult with a qualified healthcare professional for medical decisions. AI responses are not a substitute for professional medical judgment."""


__all__ = [
    # Enum
    "DisclaimerType",
    # Text constants
    "MEDICAL_DISCLAIMER_SHORT",
    "MEDICAL_DISCLAIMER_FULL",
    "AI_CONTENT_DISCLAIMER",
    "LIABILITY_DISCLAIMER",
    "EXPORT_CONTROL_NOTICE",
    "HIPAA_COMPLIANCE_NOTICE",
    "DATA_PRIVACY_NOTICE",
    "MEDICAL_TEMPLATE_BANNER",
]
