#!/bin/bash
# Create proper Xcode project for MagnetarStudio

echo "🚀 Creating Xcode project for MagnetarStudio..."
echo ""
echo "EASIEST METHOD:"
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. macOS → App"
echo "4. Product Name: MagnetarStudio"
echo "5. Interface: SwiftUI"
echo "6. Storage: SwiftData"
echo "7. Save to: $(pwd)"
echo "8. UNCHECK 'Create Git repository'"
echo ""
echo "Then:"
echo "- Delete: ContentView.swift, MagnetarStudioApp.swift, Item.swift"
echo "- Add Files: Shared/ and macOS/ folders"
echo "- Add Colors to Assets.xcassets:"
echo "  • MagnetarPrimary: #3B82F6"
echo "  • MagnetarSecondary: #8B5CF6"
echo "  • MagnetarAccent: #06B6D4"
echo ""
echo "Press ⌘R to build!"
echo ""
echo "Or just open Xcode and I'll guide you step by step."
