name: MedStation
options:
  bundleIdPrefix: com.medstation
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: MedStation
    PRODUCT_BUNDLE_IDENTIFIER: com.medstation.app
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 MedStation. CC BY 4.0."
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.medical
    INFOPLIST_KEY_NSFaceIDUsageDescription: "MedStation uses Face ID to securely authenticate you and protect patient data."
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  MedStation:
    type: application
    platform: macOS
    sources:
      - Shared
      - macOS
    resources:
      - path: Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        CODE_SIGN_ENTITLEMENTS: MedStation.entitlements
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: MedStation.entitlements
    scheme:
      environmentVariables:
        # Filter logs in Console.app by subsystem: com.medstation.app
        []
