"""
Configuration module for MagnetarCode API.

Centralized configuration constants to avoid magic numbers.
"""

from .constants import (
    AGENT_EXECUTION_RATE_LIMIT,
    AUTH_FAILURE_RATE_LIMIT,
    CHAT_CONTEXT_WINDOW,
    CHAT_STREAM_RATE_LIMIT,
    CONTEXT_BUDGET_DEFAULT,
    DEFAULT_MODEL,
    DEFAULT_TEMPERATURE,
    FILE_DELETE_RATE_LIMIT,
    FILE_WRITE_RATE_LIMIT,
    HTTP_REQUEST_TIMEOUT,
    HTTP_RESOURCE_TIMEOUT,
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES,
    JWT_REFRESH_TOKEN_EXPIRE_DAYS,
    MAX_AGENT_ITERATIONS,
    OLLAMA_CONNECT_TIMEOUT,
    OLLAMA_TIMEOUT,
    RAG_TOP_K_DEFAULT,
    TERMINAL_BUFFER_MAX_LINES,
    VECTOR_BATCH_SIZE,
    get_config_summary,
)

__all__ = [
    # Timeouts
    "OLLAMA_TIMEOUT",
    "OLLAMA_CONNECT_TIMEOUT",
    "HTTP_REQUEST_TIMEOUT",
    "HTTP_RESOURCE_TIMEOUT",
    # Rate Limits
    "CHAT_STREAM_RATE_LIMIT",
    "AGENT_EXECUTION_RATE_LIMIT",
    "FILE_WRITE_RATE_LIMIT",
    "FILE_DELETE_RATE_LIMIT",
    "AUTH_FAILURE_RATE_LIMIT",
    # Context Limits
    "CHAT_CONTEXT_WINDOW",
    "MAX_AGENT_ITERATIONS",
    "CONTEXT_BUDGET_DEFAULT",
    "RAG_TOP_K_DEFAULT",
    "TERMINAL_BUFFER_MAX_LINES",
    # Vector/Batch Processing
    "VECTOR_BATCH_SIZE",
    # Models
    "DEFAULT_MODEL",
    "DEFAULT_TEMPERATURE",
    # JWT
    "JWT_ACCESS_TOKEN_EXPIRE_MINUTES",
    "JWT_REFRESH_TOKEN_EXPIRE_DAYS",
    # Utilities
    "get_config_summary",
]
