"""Backward Compatibility Shim - use api.errors instead."""

from api.errors.responses import (
    AppException,
    app_exception_handler,
    generic_exception_handler,
    bad_request,
    unauthorized,
    forbidden,
    not_found,
    conflict,
    unprocessable_entity,
    too_many_requests,
    internal_error,
    service_unavailable,
    gateway_timeout,
    validate_model_name,
    validate_file_size,
    validate_file_format,
    check_resource_exists,
    check_permission,
    handle_rate_limit,
    logger,
    settings,
)
from api.errors.codes import ErrorCode, get_error_message

__all__ = [
    "AppException",
    "app_exception_handler",
    "generic_exception_handler",
    "bad_request",
    "unauthorized",
    "forbidden",
    "not_found",
    "conflict",
    "unprocessable_entity",
    "too_many_requests",
    "internal_error",
    "service_unavailable",
    "gateway_timeout",
    "validate_model_name",
    "validate_file_size",
    "validate_file_format",
    "check_resource_exists",
    "check_permission",
    "handle_rate_limit",
    "logger",
    "settings",
    "ErrorCode",
    "get_error_message",
]
