"""Backward Compatibility Shim - use api.workflows.models instead."""

from api.workflows.models import (
    # Re-exported enums (from enums.py via models.py)
    WorkflowTriggerType,
    StageType,
    WorkItemStatus,
    WorkItemPriority,
    AssignmentType,
    ConditionOperator,
    FieldType,
    WorkflowType,
    NotificationEvent,
    # Models
    FormFieldOption,
    FormField,
    FormDefinition,
    RoutingCondition,
    ConditionalRoute,
    AutomationConfig,
    Stage,
    WorkflowTrigger,
    Workflow,
    StageTransition,
    WorkItemAttachment,
    WorkItem,
    QueueFilter,
    Queue,
    Notification,
    WorkflowRole,
    UserRoleAssignment,
    WorkflowMetrics,
    StageMetrics,
    WorkflowSyncMessage,
    WorkItemConflict,
    CreateWorkItemRequest,
    ClaimWorkItemRequest,
    CompleteStageRequest,
    CreateWorkflowRequest,
)

__all__ = [
    # Enums
    "WorkflowTriggerType",
    "StageType",
    "WorkItemStatus",
    "WorkItemPriority",
    "AssignmentType",
    "ConditionOperator",
    "FieldType",
    "WorkflowType",
    "NotificationEvent",
    # Models
    "FormFieldOption",
    "FormField",
    "FormDefinition",
    "RoutingCondition",
    "ConditionalRoute",
    "AutomationConfig",
    "Stage",
    "WorkflowTrigger",
    "Workflow",
    "StageTransition",
    "WorkItemAttachment",
    "WorkItem",
    "QueueFilter",
    "Queue",
    "Notification",
    "WorkflowRole",
    "UserRoleAssignment",
    "WorkflowMetrics",
    "StageMetrics",
    "WorkflowSyncMessage",
    "WorkItemConflict",
    "CreateWorkItemRequest",
    "ClaimWorkItemRequest",
    "CompleteStageRequest",
    "CreateWorkflowRequest",
]
